<?php

/**
 * Product
 *
 * PHP version 8.1
 *
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.13
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dhl\Rest\Shipping\Model;

/**
 * Product Class Doc Comment
 *
 * @description Determines the DHL Paket product to be used.  * V01PAK: DHL PAKET; * V53WPAK: DHL PAKET International; * V54EPAK: DHL Europaket; * V62WP: Warenpost (will be replaced by DHL Kleinpaket from 1.1.2025); * V62KP: DHL Kleinpaket; * V66WPI: Warenpost International
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Product: string
{
    case V01_PAK = 'V01PAK';

    case V53_WPAK = 'V53WPAK';

    case V54_EPAK = 'V54EPAK';

    case V62_WP = 'V62WP';

    case V62_KP = 'V62KP';

    case V66_WPI = 'V66WPI';
}


