<?php

/**
 * ResponseItem
 *
 * PHP version 8.1
 *
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.13
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dhl\Rest\Shipping\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Dhl\Rest\Shipping\ObjectSerializer;

/**
 * ResponseItem Class Doc Comment
 *
 * @description Response for a single shipment containing status, numbers and labels
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ResponseItem implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ResponseItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'shipment_no' => 'string',
        'routing_code' => 'string',
        'return_routing_code' => 'string',
        'return_shipment_no' => 'string',
        'sstatus' => '\Dhl\Rest\Shipping\Model\RequestStatus',
        'shipment_ref_no' => 'string',
        'label' => '\Dhl\Rest\Shipping\Model\Document',
        'return_label' => '\Dhl\Rest\Shipping\Model\Document',
        'customs_doc' => '\Dhl\Rest\Shipping\Model\Document',
        'cod_label' => '\Dhl\Rest\Shipping\Model\Document',
        'validation_messages' => '\Dhl\Rest\Shipping\Model\ValidationMessageItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'shipment_no' => null,
        'routing_code' => null,
        'return_routing_code' => null,
        'return_shipment_no' => null,
        'sstatus' => null,
        'shipment_ref_no' => null,
        'label' => null,
        'return_label' => null,
        'customs_doc' => null,
        'cod_label' => null,
        'validation_messages' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'shipment_no' => false,
        'routing_code' => false,
        'return_routing_code' => false,
        'return_shipment_no' => false,
        'sstatus' => false,
        'shipment_ref_no' => false,
        'label' => false,
        'return_label' => false,
        'customs_doc' => false,
        'cod_label' => false,
        'validation_messages' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'shipment_no' => 'shipmentNo',
        'routing_code' => 'routingCode',
        'return_routing_code' => 'returnRoutingCode',
        'return_shipment_no' => 'returnShipmentNo',
        'sstatus' => 'sstatus',
        'shipment_ref_no' => 'shipmentRefNo',
        'label' => 'label',
        'return_label' => 'returnLabel',
        'customs_doc' => 'customsDoc',
        'cod_label' => 'codLabel',
        'validation_messages' => 'validationMessages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'shipment_no' => 'setShipmentNo',
        'routing_code' => 'setRoutingCode',
        'return_routing_code' => 'setReturnRoutingCode',
        'return_shipment_no' => 'setReturnShipmentNo',
        'sstatus' => 'setSstatus',
        'shipment_ref_no' => 'setShipmentRefNo',
        'label' => 'setLabel',
        'return_label' => 'setReturnLabel',
        'customs_doc' => 'setCustomsDoc',
        'cod_label' => 'setCodLabel',
        'validation_messages' => 'setValidationMessages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'shipment_no' => 'getShipmentNo',
        'routing_code' => 'getRoutingCode',
        'return_routing_code' => 'getReturnRoutingCode',
        'return_shipment_no' => 'getReturnShipmentNo',
        'sstatus' => 'getSstatus',
        'shipment_ref_no' => 'getShipmentRefNo',
        'label' => 'getLabel',
        'return_label' => 'getReturnLabel',
        'customs_doc' => 'getCustomsDoc',
        'cod_label' => 'getCodLabel',
        'validation_messages' => 'getValidationMessages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shipment_no', $data ?? [], null);
        $this->setIfExists('routing_code', $data ?? [], null);
        $this->setIfExists('return_routing_code', $data ?? [], null);
        $this->setIfExists('return_shipment_no', $data ?? [], null);
        $this->setIfExists('sstatus', $data ?? [], null);
        $this->setIfExists('shipment_ref_no', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('return_label', $data ?? [], null);
        $this->setIfExists('customs_doc', $data ?? [], null);
        $this->setIfExists('cod_label', $data ?? [], null);
        $this->setIfExists('validation_messages', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['shipment_no']) && (mb_strlen($this->container['shipment_no']) > 50)) {
            $invalidProperties[] = "invalid value for 'shipment_no', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['shipment_no']) && (mb_strlen($this->container['shipment_no']) < 0)) {
            $invalidProperties[] = "invalid value for 'shipment_no', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['routing_code']) && (mb_strlen($this->container['routing_code']) > 35)) {
            $invalidProperties[] = "invalid value for 'routing_code', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['routing_code']) && (mb_strlen($this->container['routing_code']) < 0)) {
            $invalidProperties[] = "invalid value for 'routing_code', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['return_routing_code']) && (mb_strlen($this->container['return_routing_code']) > 35)) {
            $invalidProperties[] = "invalid value for 'return_routing_code', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['return_routing_code']) && (mb_strlen($this->container['return_routing_code']) < 0)) {
            $invalidProperties[] = "invalid value for 'return_routing_code', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['return_shipment_no']) && (mb_strlen($this->container['return_shipment_no']) > 50)) {
            $invalidProperties[] = "invalid value for 'return_shipment_no', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['return_shipment_no']) && (mb_strlen($this->container['return_shipment_no']) < 0)) {
            $invalidProperties[] = "invalid value for 'return_shipment_no', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['sstatus'] === null) {
            $invalidProperties[] = "'sstatus' can't be null";
        }
        if (!is_null($this->container['shipment_ref_no']) && (mb_strlen($this->container['shipment_ref_no']) > 50)) {
            $invalidProperties[] = "invalid value for 'shipment_ref_no', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['shipment_ref_no']) && (mb_strlen($this->container['shipment_ref_no']) < 6)) {
            $invalidProperties[] = "invalid value for 'shipment_ref_no', the character length must be bigger than or equal to 6.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipment_no
     *
     * @return string|null
     */
    public function getShipmentNo(): ?string
    {
        return $this->container['shipment_no'];
    }

    /**
     * Sets shipment_no
     *
     * @param string|null $shipment_no shipment_no
     *
     * @return $this
     */
    public function setShipmentNo(?string $shipment_no): static
    {
        if (is_null($shipment_no)) {
            throw new InvalidArgumentException('non-nullable shipment_no cannot be null');
        }
        if ((mb_strlen($shipment_no) > 50)) {
            throw new InvalidArgumentException('invalid length for $shipment_no when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($shipment_no) < 0)) {
            throw new InvalidArgumentException('invalid length for $shipment_no when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['shipment_no'] = $shipment_no;

        return $this;
    }

    /**
     * Gets routing_code
     *
     * @return string|null
     */
    public function getRoutingCode(): ?string
    {
        return $this->container['routing_code'];
    }

    /**
     * Sets routing_code
     *
     * @param string|null $routing_code Routing code of the consignee address
     *
     * @return $this
     */
    public function setRoutingCode(?string $routing_code): static
    {
        if (is_null($routing_code)) {
            throw new InvalidArgumentException('non-nullable routing_code cannot be null');
        }
        if ((mb_strlen($routing_code) > 35)) {
            throw new InvalidArgumentException('invalid length for $routing_code when calling ResponseItem., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($routing_code) < 0)) {
            throw new InvalidArgumentException('invalid length for $routing_code when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['routing_code'] = $routing_code;

        return $this;
    }

    /**
     * Gets return_routing_code
     *
     * @return string|null
     */
    public function getReturnRoutingCode(): ?string
    {
        return $this->container['return_routing_code'];
    }

    /**
     * Sets return_routing_code
     *
     * @param string|null $return_routing_code Routing code of the return address
     *
     * @return $this
     */
    public function setReturnRoutingCode(?string $return_routing_code): static
    {
        if (is_null($return_routing_code)) {
            throw new InvalidArgumentException('non-nullable return_routing_code cannot be null');
        }
        if ((mb_strlen($return_routing_code) > 35)) {
            throw new InvalidArgumentException('invalid length for $return_routing_code when calling ResponseItem., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($return_routing_code) < 0)) {
            throw new InvalidArgumentException('invalid length for $return_routing_code when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['return_routing_code'] = $return_routing_code;

        return $this;
    }

    /**
     * Gets return_shipment_no
     *
     * @return string|null
     */
    public function getReturnShipmentNo(): ?string
    {
        return $this->container['return_shipment_no'];
    }

    /**
     * Sets return_shipment_no
     *
     * @param string|null $return_shipment_no return_shipment_no
     *
     * @return $this
     */
    public function setReturnShipmentNo(?string $return_shipment_no): static
    {
        if (is_null($return_shipment_no)) {
            throw new InvalidArgumentException('non-nullable return_shipment_no cannot be null');
        }
        if ((mb_strlen($return_shipment_no) > 50)) {
            throw new InvalidArgumentException('invalid length for $return_shipment_no when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($return_shipment_no) < 0)) {
            throw new InvalidArgumentException('invalid length for $return_shipment_no when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['return_shipment_no'] = $return_shipment_no;

        return $this;
    }

    /**
     * Gets sstatus
     *
     * @return \Dhl\Rest\Shipping\Model\RequestStatus
     */
    public function getSstatus(): \Dhl\Rest\Shipping\Model\RequestStatus
    {
        return $this->container['sstatus'];
    }

    /**
     * Sets sstatus
     *
     * @param \Dhl\Rest\Shipping\Model\RequestStatus $sstatus sstatus
     *
     * @return $this
     */
    public function setSstatus(\Dhl\Rest\Shipping\Model\RequestStatus $sstatus): static
    {
        if (is_null($sstatus)) {
            throw new InvalidArgumentException('non-nullable sstatus cannot be null');
        }
        $this->container['sstatus'] = $sstatus;

        return $this;
    }

    /**
     * Gets shipment_ref_no
     *
     * @return string|null
     */
    public function getShipmentRefNo(): ?string
    {
        return $this->container['shipment_ref_no'];
    }

    /**
     * Sets shipment_ref_no
     *
     * @param string|null $shipment_ref_no shipment_ref_no
     *
     * @return $this
     */
    public function setShipmentRefNo(?string $shipment_ref_no): static
    {
        if (is_null($shipment_ref_no)) {
            throw new InvalidArgumentException('non-nullable shipment_ref_no cannot be null');
        }
        if ((mb_strlen($shipment_ref_no) > 50)) {
            throw new InvalidArgumentException('invalid length for $shipment_ref_no when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($shipment_ref_no) < 6)) {
            throw new InvalidArgumentException('invalid length for $shipment_ref_no when calling ResponseItem., must be bigger than or equal to 6.');
        }

        $this->container['shipment_ref_no'] = $shipment_ref_no;

        return $this;
    }

    /**
     * Gets label
     *
     * @return \Dhl\Rest\Shipping\Model\Document|null
     */
    public function getLabel(): ?\Dhl\Rest\Shipping\Model\Document
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param \Dhl\Rest\Shipping\Model\Document|null $label label
     *
     * @return $this
     */
    public function setLabel(?\Dhl\Rest\Shipping\Model\Document $label): static
    {
        if (is_null($label)) {
            throw new InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets return_label
     *
     * @return \Dhl\Rest\Shipping\Model\Document|null
     */
    public function getReturnLabel(): ?\Dhl\Rest\Shipping\Model\Document
    {
        return $this->container['return_label'];
    }

    /**
     * Sets return_label
     *
     * @param \Dhl\Rest\Shipping\Model\Document|null $return_label return_label
     *
     * @return $this
     */
    public function setReturnLabel(?\Dhl\Rest\Shipping\Model\Document $return_label): static
    {
        if (is_null($return_label)) {
            throw new InvalidArgumentException('non-nullable return_label cannot be null');
        }
        $this->container['return_label'] = $return_label;

        return $this;
    }

    /**
     * Gets customs_doc
     *
     * @return \Dhl\Rest\Shipping\Model\Document|null
     */
    public function getCustomsDoc(): ?\Dhl\Rest\Shipping\Model\Document
    {
        return $this->container['customs_doc'];
    }

    /**
     * Sets customs_doc
     *
     * @param \Dhl\Rest\Shipping\Model\Document|null $customs_doc customs_doc
     *
     * @return $this
     */
    public function setCustomsDoc(?\Dhl\Rest\Shipping\Model\Document $customs_doc): static
    {
        if (is_null($customs_doc)) {
            throw new InvalidArgumentException('non-nullable customs_doc cannot be null');
        }
        $this->container['customs_doc'] = $customs_doc;

        return $this;
    }

    /**
     * Gets cod_label
     *
     * @return \Dhl\Rest\Shipping\Model\Document|null
     */
    public function getCodLabel(): ?\Dhl\Rest\Shipping\Model\Document
    {
        return $this->container['cod_label'];
    }

    /**
     * Sets cod_label
     *
     * @param \Dhl\Rest\Shipping\Model\Document|null $cod_label cod_label
     *
     * @return $this
     */
    public function setCodLabel(?\Dhl\Rest\Shipping\Model\Document $cod_label): static
    {
        if (is_null($cod_label)) {
            throw new InvalidArgumentException('non-nullable cod_label cannot be null');
        }
        $this->container['cod_label'] = $cod_label;

        return $this;
    }

    /**
     * Gets validation_messages
     *
     * @return \Dhl\Rest\Shipping\Model\ValidationMessageItem[]|null
     */
    public function getValidationMessages(): ?array
    {
        return $this->container['validation_messages'];
    }

    /**
     * Sets validation_messages
     *
     * @param \Dhl\Rest\Shipping\Model\ValidationMessageItem[]|null $validation_messages Optional validation messages attached to the shipment.
     *
     * @return $this
     */
    public function setValidationMessages(?array $validation_messages): static
    {
        if (is_null($validation_messages)) {
            throw new InvalidArgumentException('non-nullable validation_messages cannot be null');
        }
        $this->container['validation_messages'] = $validation_messages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


