<?php

/**
 * ManifestsApi
 * PHP version 8.1
 *
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.13
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dhl\Rest\Shipping\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Dhl\Rest\Shipping\ApiException;
use Dhl\Rest\Shipping\Configuration;
use Dhl\Rest\Shipping\HeaderSelector;
use Dhl\Rest\Shipping\FormDataProcessor;
use Dhl\Rest\Shipping\ObjectSerializer;

/**
 * ManifestsApi Class Doc Comment
 *
 * @package  Dhl\Rest\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManifestsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getManifests' => [
            'application/json',
        ],
        'manifestsPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getManifests
     *
     * Retrieve daily manifest document
     *
     * @param  string|null $billing_number Customer billingNumber number. (optional)
     * @param  string|null $date date (optional)
     * @param  string|null $include_docs Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:  * __include__: included as base64 encoded data in the response (default)  * __URL__: provided as URL reference.  Default is include the base64 encoded labels. (optional, default to 'include')
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getManifests'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Dhl\Rest\Shipping\Model\SingleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus
     */
    public function getManifests(
        ?string $billing_number = null,
        ?string $date = null,
        ?string $include_docs = 'include',
        ?string $accept_language = null,
        string $contentType = self::contentTypes['getManifests'][0]
    ): \Dhl\Rest\Shipping\Model\SingleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus {
        list($response) = $this->getManifestsWithHttpInfo($billing_number, $date, $include_docs, $accept_language, $contentType);
        return $response;
    }

    /**
     * Operation getManifestsWithHttpInfo
     *
     * Retrieve daily manifest document
     *
     * @param  string|null $billing_number Customer billingNumber number. (optional)
     * @param  string|null $date (optional)
     * @param  string|null $include_docs Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:  * __include__: included as base64 encoded data in the response (default)  * __URL__: provided as URL reference.  Default is include the base64 encoded labels. (optional, default to 'include')
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getManifests'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Dhl\Rest\Shipping\Model\SingleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus|\Dhl\Rest\Shipping\Model\RequestStatus|\Dhl\Rest\Shipping\Model\RequestStatus|\Dhl\Rest\Shipping\Model\RequestStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function getManifestsWithHttpInfo(
        ?string $billing_number = null,
        ?string $date = null,
        ?string $include_docs = 'include',
        ?string $accept_language = null,
        string $contentType = self::contentTypes['getManifests'][0]
    ): array {
        $request = $this->getManifestsRequest($billing_number, $date, $include_docs, $accept_language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\SingleManifestResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\LabelDataResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dhl\Rest\Shipping\Model\SingleManifestResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\SingleManifestResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\LabelDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getManifestsAsync
     *
     * Retrieve daily manifest document
     *
     * @param  string|null $billing_number Customer billingNumber number. (optional)
     * @param  string|null $date (optional)
     * @param  string|null $include_docs Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:  * __include__: included as base64 encoded data in the response (default)  * __URL__: provided as URL reference.  Default is include the base64 encoded labels. (optional, default to 'include')
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getManifests'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getManifestsAsync(
        ?string $billing_number = null,
        ?string $date = null,
        ?string $include_docs = 'include',
        ?string $accept_language = null,
        string $contentType = self::contentTypes['getManifests'][0]
    ): PromiseInterface {
        return $this->getManifestsAsyncWithHttpInfo($billing_number, $date, $include_docs, $accept_language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getManifestsAsyncWithHttpInfo
     *
     * Retrieve daily manifest document
     *
     * @param  string|null $billing_number Customer billingNumber number. (optional)
     * @param  string|null $date (optional)
     * @param  string|null $include_docs Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:  * __include__: included as base64 encoded data in the response (default)  * __URL__: provided as URL reference.  Default is include the base64 encoded labels. (optional, default to 'include')
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getManifests'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getManifestsAsyncWithHttpInfo(
        ?string $billing_number = null,
        ?string $date = null,
        ?string $include_docs = 'include',
        ?string $accept_language = null,
        string $contentType = self::contentTypes['getManifests'][0]
    ): PromiseInterface {
        $returnType = '\Dhl\Rest\Shipping\Model\SingleManifestResponse';
        $request = $this->getManifestsRequest($billing_number, $date, $include_docs, $accept_language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getManifests'
     *
     * @param  string|null $billing_number Customer billingNumber number. (optional)
     * @param  string|null $date (optional)
     * @param  string|null $include_docs Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:  * __include__: included as base64 encoded data in the response (default)  * __URL__: provided as URL reference.  Default is include the base64 encoded labels. (optional, default to 'include')
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getManifests'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getManifestsRequest(
        ?string $billing_number = null,
        ?string $date = null,
        ?string $include_docs = 'include',
        ?string $accept_language = null,
        string $contentType = self::contentTypes['getManifests'][0]
    ): Request {






        $resourcePath = '/manifests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $billing_number,
            'billingNumber', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_docs,
            'includeDocs', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('dhl-api-key');
        if ($apiKey !== null) {
            $headers['dhl-api-key'] = $apiKey;
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation manifestsPost
     *
     * Mark shipments as being ready for shipping
     *
     * @param  \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request Manifest request taking multiple input elements (required)
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  bool|null $all Specify if all applicable shipments shall be marked as being ready for shipping. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manifestsPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Dhl\Rest\Shipping\Model\MultipleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus
     */
    public function manifestsPost(
        \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request,
        ?string $accept_language = null,
        ?bool $all = false,
        string $contentType = self::contentTypes['manifestsPost'][0]
    ): \Dhl\Rest\Shipping\Model\MultipleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus {
        list($response) = $this->manifestsPostWithHttpInfo($shipment_manifesting_request, $accept_language, $all, $contentType);
        return $response;
    }

    /**
     * Operation manifestsPostWithHttpInfo
     *
     * Mark shipments as being ready for shipping
     *
     * @param  \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request Manifest request taking multiple input elements (required)
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  bool|null $all Specify if all applicable shipments shall be marked as being ready for shipping. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manifestsPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Dhl\Rest\Shipping\Model\MultipleManifestResponse|\Dhl\Rest\Shipping\Model\LabelDataResponse|\Dhl\Rest\Shipping\Model\RequestStatus|\Dhl\Rest\Shipping\Model\RequestStatus|\Dhl\Rest\Shipping\Model\RequestStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function manifestsPostWithHttpInfo(
        \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request,
        ?string $accept_language = null,
        ?bool $all = false,
        string $contentType = self::contentTypes['manifestsPost'][0]
    ): array {
        $request = $this->manifestsPostRequest($shipment_manifesting_request, $accept_language, $all, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 207:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\MultipleManifestResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\LabelDataResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dhl\Rest\Shipping\Model\MultipleManifestResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\MultipleManifestResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\LabelDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dhl\Rest\Shipping\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation manifestsPostAsync
     *
     * Mark shipments as being ready for shipping
     *
     * @param  \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request Manifest request taking multiple input elements (required)
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  bool|null $all Specify if all applicable shipments shall be marked as being ready for shipping. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manifestsPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function manifestsPostAsync(
        \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request,
        ?string $accept_language = null,
        ?bool $all = false,
        string $contentType = self::contentTypes['manifestsPost'][0]
    ): PromiseInterface {
        return $this->manifestsPostAsyncWithHttpInfo($shipment_manifesting_request, $accept_language, $all, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation manifestsPostAsyncWithHttpInfo
     *
     * Mark shipments as being ready for shipping
     *
     * @param  \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request Manifest request taking multiple input elements (required)
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  bool|null $all Specify if all applicable shipments shall be marked as being ready for shipping. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manifestsPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function manifestsPostAsyncWithHttpInfo(
        \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request,
        ?string $accept_language = null,
        ?bool $all = false,
        string $contentType = self::contentTypes['manifestsPost'][0]
    ): PromiseInterface {
        $returnType = '\Dhl\Rest\Shipping\Model\MultipleManifestResponse';
        $request = $this->manifestsPostRequest($shipment_manifesting_request, $accept_language, $all, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'manifestsPost'
     *
     * @param  \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request Manifest request taking multiple input elements (required)
     * @param  string|null $accept_language Control the APIs response language via locale abbreviation. English (en-US) and german (de-DE) are supported. If not specified, the default is english. (optional)
     * @param  bool|null $all Specify if all applicable shipments shall be marked as being ready for shipping. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manifestsPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function manifestsPostRequest(
        \Dhl\Rest\Shipping\Model\ShipmentManifestingRequest $shipment_manifesting_request,
        ?string $accept_language = null,
        ?bool $all = false,
        string $contentType = self::contentTypes['manifestsPost'][0]
    ): Request {

        // verify the required parameter 'shipment_manifesting_request' is set
        if ($shipment_manifesting_request === null || (is_array($shipment_manifesting_request) && count($shipment_manifesting_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $shipment_manifesting_request when calling manifestsPost'
            );
        }




        $resourcePath = '/manifests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $all,
            'all', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($shipment_manifesting_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($shipment_manifesting_request));
            } else {
                $httpBody = $shipment_manifesting_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('dhl-api-key');
        if ($apiKey !== null) {
            $headers['dhl-api-key'] = $apiKey;
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
